define({
    sheet1: [
        ["GeoSpace-Sea Metadata Form", null],
        ["M = mandatory, C = conditional, O = optional", null],
        ["General Information", null],
        ["M", "Metadata identifier", null],
        ["M", "Metadata language", null],
        ["M", "Metadata data stamp", null],
        ["M", "Metadata created date", null],
        ["M", "Standard name", null],
        ["M", "Metadata standard version", null],
        ["Metadata Identification", null],
        ["M", "Citation title", null],
        ["M", "Date", null],
        ["M", "Date type", null],
        ["M", "Publisher", null],
        ["O", "Citation language", null],
        ["M", "Abstract", null],
        ["M", "Maintenance and Update frequency", null],
        ["M", "Geometric Object Type", null],
        ["M", "Reference System", null],
        ["M", "Last uploaded date", null],
        ["M", "Keywords", null],
        ["M", "Use constraints", null],
        ["O", "Other constraints", null],
        ["M", "Classification", null],
        ["O", "Sensitivity Classification", null],
        ["C", "Information Marker", null],
        ["M", "Data lineage", null],
        ["M", "Contact person", null],
        ["M", "Organisation", null],
        ["M", "Role", null],
        ["M", "Telephone", null],
        ["M", "Email", null],
        ["O", "Citation language", null],
        ["O", "Purpose", null],
        ["O", "Status", null],
        ["O", "Feature Count", null],
        ["O", "Scale", null],
        ["O", "Data theme", null],
        ["O", "Marine Data theme (Level III)", null],
        ["C", "Marine Data theme (Level II)", null]
    ],
    sheet3: [
        ["Data Quality", null],
        ["M = mandatory, C = conditional, O = optional", null],
        ["M", "Data Quality Scope", null],
        ["M", "Name Type", null],
        ["M", "Name", null],
        ["O", "Alias", null],
        ["M", "Element name", null],
        ["M", "Basic measure", null],
        ["O", "Parameter", null],
        ["M", "Value type", null],
        ["O", "Value structure", null],
        ["M", "Definition", null],
        ["O", "Description", null],
        ["O", "Source reference", null],
        ["M", "Example", null],
        ["M", "Identifier", null],
        ["M", "Acceptance Quality Limit (AQL)", null],
        ["O", "Feature type", null],
        ["O", "Error count", null],
        ["O", "Error rate", null],
        ["M", "Pass", null],
        ["O", "Evaluation Method type", null],
        ["O", "Evaluation method description", null],
        ["O", "Evaluation method procedure", null],
        ["O", "Date", null],
        ["O", "Value unit", null],
        ["M", "Value", null]
    ],
    sheet4: [
        ["Overview of Metadata", null],
        ["M = mandatory, C = conditional, O = optional", null],
        ["M", "Horizontal Coordinate System", null],
        ["M", "West Bounding Longitude", null],
        ["M", "South Bounding Longitude", null],
        ["M", "East Bounding Longitude", null],
        ["M", "North Bounding Longitude", null],
        ["O", "Browse Graphic", null],
        ["O", "Vertical Coordinate System", null],
        ["O", "Datum", null],
        ["O", "Spheroid", null],
        ["O", "Major Axis", null],
        ["O", "Minor Axis", null],
        ["O", "Prime Meridian", null],
        ["O", "Angular Unit", null],
        ["O", "Projection", null],
        ["O", "False Easting", null],
        ["O", "False Northing", null],
        ["O", "Central Meridian", null],
        ["O", "Scale Factor", null],
        ["O", "Latitude of Origin", null],
        ["O", "Linear Unit", null],
        ["O", "Link Layers", null]
    ]

});